/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualizacao;
import Controle.Conexao;
import Modelagem.Usuario;
import Modelagem.Vendedor;

import java.awt.CardLayout;
import java.awt.Toolkit;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author dsm-2
 */
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
        setIcon();
    }
    Usuario usu = new Usuario();
    Vendedor vend = new Vendedor();
    Conexao conn = new Conexao();
    
    public String consultarUsuario(String cpf, String senha){
        try{
            ResultSet rs;
            String sql = "SELECT id_cliente FROM Clientes where cpf_cliente = '"+cpf+"' and senha_cliente = '"+senha+"'";
            rs = conn.RetornarResultset(sql);
            rs.beforeFirst();
            if(rs.next()){
                usu.setId(Integer.parseInt(rs.getString(1)));
                return "Cliente";
            }else if(!rs.next()){
                sql="SELECT id_vendedor FROM Vendedor where cpf_vendedor = '"+cpf+"' and senha_vendedor = '"+senha+"'";
                rs = conn.RetornarResultset(sql);
                rs.beforeFirst();
                if(rs.next()){
                    vend.setId(Integer.parseInt(rs.getString(1)));
                    return "Vendedor";
                }else{
                    return "";
                }
            }else{
                return "";
            }
        }catch(SQLException ex){
              JOptionPane.showMessageDialog(null, "Erro ao executar o comando: "+ex);
              return "";
        }
    }
    
    public int consultarCPF(String cpf){
        try{
            ResultSet rs;
            String sql = "SELECT cpf_cliente FROM Clientes where cpf_cliente = '"+cpf+"'";
            rs = conn.RetornarResultset(sql);
            rs.beforeFirst();
            if(rs.next()){
                return 1;
            }else if(!rs.next()){
                sql="SELECT cpf_vendedor FROM Vendedor where cpf_vendedor = '"+cpf+"'";
                rs = conn.RetornarResultset(sql);
                rs.beforeFirst();
                if(!rs.next()){
                    return 0;
                }else{
                    return 1;
                }
            }else{
                return 1;
            }
        }catch(SQLException ex){
              JOptionPane.showMessageDialog(null, "Erro ao executar o comando: "+ex);
              return 1;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pWrapper = new javax.swing.JPanel();
        pInicio = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnLogar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pLogar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnLogar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        tipoCad = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnIrCadVend = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        btnIrCadCons = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cadCons = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEmailcons = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCadastrarCons = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNomecons = new javax.swing.JTextField();
        txtTelcons = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtSenhacons = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        txtSenhacons2 = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        txtCidadecons = new javax.swing.JTextField();
        txtUfcons = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtCpfcons = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cadVend = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtEmailvend = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnCadastrarCons1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtNomevend = new javax.swing.JTextField();
        txtCpfvend = new javax.swing.JFormattedTextField();
        jLabel29 = new javax.swing.JLabel();
        txtSenhavend = new javax.swing.JPasswordField();
        jLabel30 = new javax.swing.JLabel();
        txtSenhavend2 = new javax.swing.JPasswordField();
        txtCidadevend = new javax.swing.JTextField();
        txtUfvend = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btnDinheiro = new javax.swing.JCheckBox();
        btnDebito = new javax.swing.JCheckBox();
        btnCredito = new javax.swing.JCheckBox();
        btnPix = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();
        txtTelvend = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sr. Camelo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setResizable(false);
        setSize(new java.awt.Dimension(390, 861));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pWrapper.setLayout(new java.awt.CardLayout());

        pInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        btnLogar.setBackground(new java.awt.Color(255, 255, 255));
        btnLogar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnLogar.setForeground(new java.awt.Color(92, 172, 14));
        btnLogar.setText("Logar");
        btnLogar.setBorder(null);
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Não tenho uma conta");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel2)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(516, Short.MAX_VALUE)
                .addComponent(btnLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(297, 297, 297))
        );

        pInicio.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fundo-tela-inicial.png"))); // NOI18N
        pInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pWrapper.add(pInicio, "Inicio");

        pLogar.setBackground(new java.awt.Color(255, 103, 0));
        pLogar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 103, 0));
        jLabel3.setText("Login");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 61, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-pessoa.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 109, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(82, 172, 14));
        jLabel5.setText("CPF");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(82, 172, 14));
        jLabel6.setText("Senha");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        txtSenha.setForeground(new java.awt.Color(255, 103, 0));
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 420, 281, 23));

        btnLogar1.setBackground(new java.awt.Color(255, 103, 0));
        btnLogar1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnLogar1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogar1.setText("Logar");
        btnLogar1.setBorder(null);
        btnLogar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 526, 235, 69));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(92, 172, 14));
        jLabel7.setText("Não tenho uma conta");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 610, -1, -1));

        txtCpf.setForeground(new java.awt.Color(255, 103, 0));
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 281, 26));

        pLogar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 390, 770));

        pWrapper.add(pLogar, "logar");

        tipoCad.setBackground(new java.awt.Color(255, 107, 0));
        tipoCad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 103, 0));
        jLabel17.setText("Criar Cadastro");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-pessoa.png"))); // NOI18N
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 109, -1, -1));

        btnIrCadVend.setBackground(new java.awt.Color(255, 103, 0));
        btnIrCadVend.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnIrCadVend.setForeground(new java.awt.Color(255, 255, 255));
        btnIrCadVend.setText("Sou Vendedor");
        btnIrCadVend.setBorder(null);
        btnIrCadVend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIrCadVendMouseClicked(evt);
            }
        });
        jPanel4.add(btnIrCadVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 428, 235, 69));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(92, 172, 14));
        jLabel21.setText("Já tenho uma conta");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, -1, -1));

        btnIrCadCons.setBackground(new java.awt.Color(255, 103, 0));
        btnIrCadCons.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnIrCadCons.setForeground(new java.awt.Color(255, 255, 255));
        btnIrCadCons.setText("Sou Consumidor");
        btnIrCadCons.setBorder(null);
        btnIrCadCons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIrCadConsMouseClicked(evt);
            }
        });
        jPanel4.add(btnIrCadCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 309, 235, 69));

        tipoCad.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 390, 770));

        pWrapper.add(tipoCad, "tipoCad");

        cadCons.setBackground(new java.awt.Color(255, 103, 0));
        cadCons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 103, 0));
        jLabel8.setText("Cadastro Consumidor");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-pessoa.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 109, -1, -1));

        txtEmailcons.setForeground(new java.awt.Color(255, 103, 0));
        jPanel3.add(txtEmailcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 281, 26));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(82, 172, 14));
        jLabel10.setText("Email");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(82, 172, 14));
        jLabel11.setText("Senha");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        btnCadastrarCons.setBackground(new java.awt.Color(255, 103, 0));
        btnCadastrarCons.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCadastrarCons.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarCons.setText("Cadastrar");
        btnCadastrarCons.setBorder(null);
        btnCadastrarCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarConsActionPerformed(evt);
            }
        });
        jPanel3.add(btnCadastrarCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 700, 235, 69));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(92, 172, 14));
        jLabel12.setText("Sou Vendedor");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 810, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(82, 172, 14));
        jLabel13.setText("Nome");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(82, 172, 14));
        jLabel14.setText("CPF");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        txtNomecons.setForeground(new java.awt.Color(255, 103, 0));
        jPanel3.add(txtNomecons, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 281, 26));

        txtTelcons.setForeground(new java.awt.Color(255, 104, 0));
        try {
            txtTelcons.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(txtTelcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 281, 26));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(82, 172, 14));
        jLabel15.setText("Telefone");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        txtSenhacons.setForeground(new java.awt.Color(255, 104, 0));
        jPanel3.add(txtSenhacons, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 281, 26));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(82, 172, 14));
        jLabel16.setText("Confirmar Senha");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        txtSenhacons2.setForeground(new java.awt.Color(255, 104, 0));
        jPanel3.add(txtSenhacons2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 281, 26));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(82, 172, 14));
        jLabel19.setText("Cidade");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, -1, -1));

        txtCidadecons.setForeground(new java.awt.Color(255, 103, 0));
        jPanel3.add(txtCidadecons, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 180, 26));

        txtUfcons.setForeground(new java.awt.Color(255, 103, 0));
        txtUfcons.setToolTipText("");
        txtUfcons.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUfconsKeyTyped(evt);
            }
        });
        jPanel3.add(txtUfcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, 90, 26));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(82, 172, 14));
        jLabel20.setText("UF");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, -1, -1));

        jLabel35.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(92, 172, 14));
        jLabel35.setText("Já tenho uma conta");
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 780, -1, -1));

        txtCpfcons.setForeground(new java.awt.Color(255, 103, 0));
        try {
            txtCpfcons.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(txtCpfcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 281, 26));

        cadCons.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 390, 870));

        jScrollPane2.setViewportView(cadCons);

        pWrapper.add(jScrollPane2, "cadCons");

        cadVend.setBackground(new java.awt.Color(255, 103, 0));
        cadVend.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 103, 0));
        jLabel22.setText("Cadastro Vendedor");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carrinho_verde.png"))); // NOI18N
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 109, -1, -1));

        txtEmailvend.setForeground(new java.awt.Color(255, 103, 0));
        jPanel5.add(txtEmailvend, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 281, 26));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(82, 172, 14));
        jLabel24.setText("Email");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(82, 172, 14));
        jLabel25.setText("Senha");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        btnCadastrarCons1.setBackground(new java.awt.Color(255, 103, 0));
        btnCadastrarCons1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCadastrarCons1.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarCons1.setText("Cadastrar");
        btnCadastrarCons1.setBorder(null);
        btnCadastrarCons1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCons1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnCadastrarCons1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 920, 235, 69));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(92, 172, 14));
        jLabel26.setText("Sou Cliente");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1030, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(82, 172, 14));
        jLabel27.setText("Nome");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(82, 172, 14));
        jLabel28.setText("CPF");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        txtNomevend.setForeground(new java.awt.Color(255, 103, 0));
        jPanel5.add(txtNomevend, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 281, 26));

        txtCpfvend.setForeground(new java.awt.Color(255, 104, 0));
        try {
            txtCpfvend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(txtCpfvend, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 281, 26));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(82, 172, 14));
        jLabel29.setText("Telefone");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        txtSenhavend.setForeground(new java.awt.Color(255, 104, 0));
        jPanel5.add(txtSenhavend, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 281, 26));

        jLabel30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(82, 172, 14));
        jLabel30.setText("Confirmar Senha");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        txtSenhavend2.setForeground(new java.awt.Color(255, 104, 0));
        jPanel5.add(txtSenhavend2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 281, 26));

        txtCidadevend.setForeground(new java.awt.Color(255, 103, 0));
        jPanel5.add(txtCidadevend, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 180, 26));

        txtUfvend.setForeground(new java.awt.Color(255, 103, 0));
        txtUfvend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUfvendKeyTyped(evt);
            }
        });
        jPanel5.add(txtUfvend, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, 90, 26));

        jLabel32.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(82, 172, 14));
        jLabel32.setText("UF");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, -1, -1));

        jLabel33.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(82, 172, 14));
        jLabel33.setText("Cidade");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, -1, -1));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(82, 172, 14));
        jLabel31.setText("Formas de Pagamento");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 700, -1, -1));

        btnDinheiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDinheiro.setForeground(new java.awt.Color(82, 172, 14));
        btnDinheiro.setText("Dinheiro");
        jPanel5.add(btnDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 730, -1, -1));

        btnDebito.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDebito.setForeground(new java.awt.Color(82, 172, 14));
        btnDebito.setText("Débito");
        jPanel5.add(btnDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 770, -1, -1));

        btnCredito.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCredito.setForeground(new java.awt.Color(82, 172, 14));
        btnCredito.setText("Crédito");
        jPanel5.add(btnCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 810, -1, -1));

        btnPix.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPix.setForeground(new java.awt.Color(82, 172, 14));
        btnPix.setText("Pix");
        jPanel5.add(btnPix, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 850, -1, -1));

        jLabel34.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(92, 172, 14));
        jLabel34.setText("Já tenho uma conta");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1000, -1, -1));

        txtTelvend.setForeground(new java.awt.Color(255, 104, 0));
        try {
            txtTelvend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(txtTelvend, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 281, 26));

        cadVend.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 390, 1070));

        jScrollPane1.setViewportView(cadVend);

        pWrapper.add(jScrollPane1, "cadVend");

        getContentPane().add(pWrapper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 860));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
        CardLayout cl = (CardLayout) pWrapper.getLayout();
        cl.show(pWrapper, "logar");
    }//GEN-LAST:event_btnLogarActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        CardLayout cl = (CardLayout) pWrapper.getLayout();
        cl.show(pWrapper, "tipoCad");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        CardLayout cl = (CardLayout) pWrapper.getLayout();
        cl.show(pWrapper, "logar");
    }//GEN-LAST:event_jLabel21MouseClicked

    private void btnIrCadConsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIrCadConsMouseClicked
        CardLayout cl = (CardLayout) pWrapper.getLayout();
        cl.show(pWrapper, "cadCons");
    }//GEN-LAST:event_btnIrCadConsMouseClicked

    private void btnIrCadVendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIrCadVendMouseClicked
        CardLayout cl = (CardLayout) pWrapper.getLayout();
        cl.show(pWrapper, "cadVend");
    }//GEN-LAST:event_btnIrCadVendMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        CardLayout cl = (CardLayout) pWrapper.getLayout();
        cl.show(pWrapper, "tipoCad");
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        CardLayout cl = (CardLayout) pWrapper.getLayout();
        cl.show(pWrapper, "logar");
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        CardLayout cl = (CardLayout) pWrapper.getLayout();
        cl.show(pWrapper, "cadCons");
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        CardLayout cl = (CardLayout) pWrapper.getLayout();
        cl.show(pWrapper, "cadVend");
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        CardLayout cl = (CardLayout) pWrapper.getLayout();
        cl.show(pWrapper, "logar");
    }//GEN-LAST:event_jLabel35MouseClicked

    private void btnCadastrarConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarConsActionPerformed
        String senha = new String(txtSenhacons.getPassword()).trim();
        String ConfirmarSenha = new String(txtSenhacons2.getPassword()).trim();
        int existeCpf;
        
        usu.setNome(txtNomecons.getText());
        usu.setCpf(txtCpfcons.getText());
        usu.setEmail(txtEmailcons.getText());
        usu.setTel(txtTelcons.getText());
        usu.setSenha(senha);
        usu.setEstado(txtUfcons.getText());
        usu.setCidade(txtCidadecons.getText());
        existeCpf = consultarCPF(txtCpfcons.getText());
        if (senha.equals(ConfirmarSenha)){
            if(existeCpf==0){
                usu.cadastrarCliente();
                txtNomecons.setText("");
                txtCpfcons.setText("");
                txtEmailcons.setText("");
                txtTelcons.setText("");
                txtSenhacons.setText("");
                txtSenhacons2.setText("");
                txtUfcons.setText("");
                txtCidadecons.setText("");

                CardLayout cl = (CardLayout) pWrapper.getLayout();
                cl.show(pWrapper, "logar");
            }else{
              JOptionPane.showMessageDialog(null, "CPF já cadastrado");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Senhas são diferentes");
            txtSenhacons2.setText("");
        }
        
    }//GEN-LAST:event_btnCadastrarConsActionPerformed

    private void btnCadastrarCons1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCons1ActionPerformed
        String senha = new String(txtSenhavend.getPassword()).trim();
        String ConfirmarSenha = new String(txtSenhavend2.getPassword()).trim();
        String tiposPag = "";
        int existeCpf;
        
        vend.setNome(txtNomevend.getText());
        vend.setCpf(txtCpfvend.getText());
        vend.setEmail(txtEmailvend.getText());
        vend.setTel(txtTelvend.getText());
        vend.setSenha(senha);
        vend.setEstado(txtUfvend.getText());
        vend.setCidade(txtCidadevend.getText());
        
        if(btnDinheiro.isSelected()){
            tiposPag = tiposPag.concat("Dinheiro");
        }
        if(btnDebito.isSelected()){
            tiposPag = tiposPag.concat("Debito");
        }
        if(btnCredito.isSelected()){
            tiposPag = tiposPag.concat("Credito");
        }
        if(btnPix.isSelected()){
            tiposPag = tiposPag.concat("Pix");
        }
        vend.setFormaPag(tiposPag);
        
        existeCpf = consultarCPF(txtCpfvend.getText());
        
        if (senha.equals(ConfirmarSenha)){
            if(existeCpf==0){
                vend.cadastrarVendedor();
              
                txtNomevend.setText("");
                txtCpfvend.setText("");
                txtEmailvend.setText("");
                txtTelvend.setText("");
                txtSenhavend.setText("");
                txtSenhavend2.setText("");
                txtUfvend.setText("");
                txtCidadevend.setText("");
                btnDinheiro.setSelected(false);
                btnDebito.setSelected(false);
                btnCredito.setSelected(false);
                btnPix.setSelected(false);
        
                CardLayout cl = (CardLayout) pWrapper.getLayout();
                cl.show(pWrapper, "logar");
            }else{
              JOptionPane.showMessageDialog(null, "CPF já cadastrado");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Senha Divergentes");
            txtSenhavend2.setText("");
        }
        
        
    }//GEN-LAST:event_btnCadastrarCons1ActionPerformed

    private void btnLogar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogar1ActionPerformed
        String cpf = txtCpf.getText();
        String senha = new String(txtSenha.getPassword()).trim();
        String tipo = consultarUsuario(cpf, senha);
        
        if(tipo.equals("Cliente")){
            frmMapaCliente frm = new frmMapaCliente();
            frm.usu.setarIdCliente(usu.getId());
            frm.setVisible(true);
        }else if(tipo.equals("Vendedor")){
            frmVendedor form = new frmVendedor();
            form.vend.setarIdVendedor(vend.getId());
            int valor = form.vendedorNovo();
            //System.out.println(valor);
            //CardLayout cl = (CardLayout) form.pWrapper.getLayout();
            if(valor==1){
                form.setVisible(true);
            }else{
                frmMapaVendedor frm = new frmMapaVendedor();
                frm.vend.setarIdVendedor(vend.getId());
                frm.setVisible(true); 
            }
        }else{
            JOptionPane.showMessageDialog(null, "Usuario ou senha incorretos");
        }
        this.dispose();
    }//GEN-LAST:event_btnLogar1ActionPerformed

    private void txtUfconsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUfconsKeyTyped
        if(txtUfcons.getText().length()>=2) {  
        evt.consume();
        }
    }//GEN-LAST:event_txtUfconsKeyTyped

    private void txtUfvendKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUfvendKeyTyped
        if(txtUfvend.getText().length()>=2) {  
        evt.consume();
        }
    }//GEN-LAST:event_txtUfvendKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmInicio frm = new frmInicio();
                frm.setVisible(true);
                /*new frmInicio().setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCons;
    private javax.swing.JButton btnCadastrarCons1;
    private javax.swing.JCheckBox btnCredito;
    private javax.swing.JCheckBox btnDebito;
    private javax.swing.JCheckBox btnDinheiro;
    private javax.swing.JButton btnIrCadCons;
    private javax.swing.JButton btnIrCadVend;
    private javax.swing.JButton btnLogar;
    private javax.swing.JButton btnLogar1;
    private javax.swing.JCheckBox btnPix;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cadCons;
    private javax.swing.JPanel cadVend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pInicio;
    private javax.swing.JPanel pLogar;
    private javax.swing.JPanel pWrapper;
    private javax.swing.JPanel tipoCad;
    private javax.swing.JTextField txtCidadecons;
    private javax.swing.JTextField txtCidadevend;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtCpfcons;
    private javax.swing.JFormattedTextField txtCpfvend;
    private javax.swing.JTextField txtEmailcons;
    private javax.swing.JTextField txtEmailvend;
    private javax.swing.JTextField txtNomecons;
    private javax.swing.JTextField txtNomevend;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenhacons;
    private javax.swing.JPasswordField txtSenhacons2;
    private javax.swing.JPasswordField txtSenhavend;
    private javax.swing.JPasswordField txtSenhavend2;
    private javax.swing.JFormattedTextField txtTelcons;
    private javax.swing.JFormattedTextField txtTelvend;
    private javax.swing.JTextField txtUfcons;
    private javax.swing.JTextField txtUfvend;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("src/Imagens/logoBL.png")));
    }
}
